"""empty message

Revision ID: 7a91d6b204ea
Revises: 
Create Date: 2023-10-15 13:44:16.100102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a91d6b204ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_price_tracker')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.create_table('security_price_tracker',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name='security_price_tracker_security_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='security_price_tracker_pkey'),
    sa.UniqueConstraint('security_id', name='security_price_tracker_security_id_key')
    )
    # ### end Alembic commands ###
