"""empty message

Revision ID: 0af0a84fc987
Revises: 
Create Date: 2023-10-09 21:10:56.507651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0af0a84fc987'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_price_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_column('last_price')
        batch_op.drop_column('description')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('ticker',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    op.drop_table('security_price_tracker')
    # ### end Alembic commands ###
